### ISSUE TITLE
View -> Controller action

### ISSUE THREAD

**Issue by toneplex** [vladas/phpstorm-zf1#1]
@vladas thanks for making this plugin. Could you please add the ability to jump from a view back to the controller action?

**Comment by vladas** [comment]
Hi @toneplex, it's awesome to hear feedback. I'll see what I can do.

**Comment by vladas** [comment]
@toneplex, done. You check it out once it's approved by moderators.

**Comment by toneplex** [comment]
Thanks @vladas. The update is working nicely. So much quicker to move both ways now.
